set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL

CREATE USER ${ORG_API_APP_DB_USER} WITH PASSWORD '$(cat /run/secrets/org_api_app_db_password)';
CREATE SCHEMA IF NOT EXISTS ${ORG_API_APP_DB_SCHEMA} AUTHORIZATION ${ORG_API_APP_DB_USER};

GRANT CREATE, USAGE ON SCHEMA ${ORG_API_APP_DB_SCHEMA} TO ${ORG_API_APP_DB_USER};
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA ${ORG_API_APP_DB_SCHEMA} TO ${ORG_API_APP_DB_USER};
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA ${ORG_API_APP_DB_SCHEMA} TO ${ORG_API_APP_DB_USER};
ALTER DEFAULT PRIVILEGES IN SCHEMA ${ORG_API_APP_DB_SCHEMA} GRANT ALL PRIVILEGES ON TABLES TO ${ORG_API_APP_DB_USER};
ALTER DEFAULT PRIVILEGES IN SCHEMA ${ORG_API_APP_DB_SCHEMA} GRANT ALL PRIVILEGES ON SEQUENCES TO ${ORG_API_APP_DB_USER};

ALTER USER ${ORG_API_APP_DB_USER} SET search_path TO ${ORG_API_APP_DB_SCHEMA}, public;

EOSQL